### ISSUE TITLE
Local machine path in file bundle_adjustment_ceres.cpp

### ISSUE THREAD

**Issue by anshium** [zeelbhatt/bundle_adjustment.github.io#2]
In the file bundle_adjustment_ceres.cpp, there is a line which uses the author's local machine and for good reasons, it would not work on other machines. As an easy fix, I have used the relative path in a pull request, assuming the executable would be called where the problem-16-22106-pre.txt exists.

**Comment by anshium** [comment]
A Pull Request has been created to fix this.

**Comment by zeelbhatt** [comment]
correction merged
